### ISSUE TITLE
Question: procedural sequence generation

### ISSUE THREAD

**Issue by RomanHargrave** [DmitryOlshansky/pry#5]
I'm writing a parser for ruby, as an experiment in D, and was considering Pry as an option for parsing due to my preference for in-language DSLs.

Ruby has an interesting rule for string literals, essentially, you can define a string literal according to the following grammar, where `char` is any printable non-alphanumeric ASCII character - `STRING2 : %(Q|q|x|r|S|s) char {any_char} char`. For example, `"a string"`, `%{a string}` and `%q{a string}` are equivalent for our intents.

Declaring each variant separately and explicitly would result in a huge number of rules to write, and then maintain.

Pry's lack of documentation, outside of the examples, has currently led me to believe that there is no Pry-idiomatic expression to match all of these variants _as well as_ ensure they are terminated with the same delimiter.

I'm left with a few options, assuming that what I what is not expressible within the framework of Pry: 

* Use CTFE to generate a sequence for every possible variant

* Find a way to write a custom parser which is compatible with Pry

**Comment by RomanHargrave** [comment]
Having read the source for Pry, things are a lot less complicated than I though, at least for the purpose of writing a custom parser.

I couldn't find a parser in the Pry source that does what I want (the closest was Delimited, but that's for lists it would appear), so I'm closing this. Though if you have any suggestions, I'm still interested.

**Comment by DmitryOlshansky** [comment]
You are right, there is no out of the box parser for this case of delimiter sequence delimiter. I think indeed that indeed adding custom parser for this case is the way forward.

Also sorry for the poor state of the documentation.

**Comment by RomanHargrave** [comment]
That's what I've ended up doing.
